### ISSUE TITLE
pimpleDyfoam crashes

### ISSUE THREAD

**Issue by novicefoamer** [blueCFD/Core#45] opened 2017-07-26 02:20 UTC
pimpleDyfoam crashes, I have tried running a parallel solve , but it crashed saying mpi run error.
So when I tried to run it without using the parallel solve, I get an error saying
-> FOAM FATAL ERROR: 
Not implemented

    From function Foam::tmp<Foam::Field<Type> > Foam::coupledFvPatchField<Type>::snGrad() const [with Type = Foam::Vector<double>]
    in file ./fields/fvPatchFields/basic/coupled/coupledFvPatchField.H at line 150.

**Comment by wyldckat** [comment] 2017-07-26 08:39
That's a bit strange... does it give any other error messages before and after that message block? Because it should state on which field it's having this problem.

If it doesn't give any other details, then what boundary types do you have in your case that are using coupling?

**Comment by novicefoamer** [comment] 2017-07-28 14:16
[pimpleDyMFoam.txt](https://github.com/blueCFD/Core/files/1183288/pimpleDyMFoam.txt)
I have enclosed the file in this email

**Comment by wyldckat** [comment] 2017-07-28 14:44
That is a bit annoying... OpenFOAM should have complained about the name of the patch where it had the problem.

Can you please share the "U" file? Or if the names of the boundary conditions can't be made available publically, then please run the following command (in the blueCFD-Core terminal) to get a summary of the types of boundaries being used:
```
grep type 0/U
```

While were are at it, might as well check the types in `constant/polyMesh/boundary` as well:
```
grep type constant/polyMesh/boundary
```

**Comment by novicefoamer** [comment] 2017-07-28 15:30
I have enclosed the U file in this comment
[U -text.txt](https://github.com/blueCFD/Core/files/1183508/U.-text.txt)

**Comment by novicefoamer** [comment] 2017-07-28 15:31
I have placed the grep file types in this comment
![capture](https://user-images.githubusercontent.com/30294156/28724520-48381b84-7388-11e7-82a0-c0f475bffeb5.JPG)
![capture1](https://user-images.githubusercontent.com/30294156/28724528-4dec4b54-7388-11e7-8f8f-efcb4f948a94.JPG)

**Comment by wyldckat** [comment] 2017-07-28 15:45
The boundaries that are defined as type `cyclicAMI` are the ones complaining about the `coupled` type boundary not handling `snGrad`.

A few questions:

 1. Based on which tutorial case are you configuring your case?

 2. What is the boundary condition you have in the `0/U` field file that is associated to the boundaries of type `cyclicAMI` in the file `constant/polyMesh/boundary`?

**Comment by novicefoamer** [comment] 2017-07-28 15:57
I have used propeller case
I didnt understand the second question, so I have placed the boundary file in this comment
[boundary.txt](https://github.com/blueCFD/Core/files/1183577/boundary.txt)

**Comment by wyldckat** [comment] 2017-07-28 16:07
Thanks, this way I know the names of the boundaries, so the question now becomes: What velocity conditions did you assign for the patches AMI1 and AMI2?

In addition, what is defined in the file `0/include/fixedInlet`?

**Comment by novicefoamer** [comment] 2017-07-28 16:32
I have put the value in the dynamicMeshdict, I put the velocity as 158rad/sec .
I have included the file in this comment.
[dynamicMeshDict.txt](https://github.com/blueCFD/Core/files/1183690/dynamicMeshDict.txt)
The include file has two files, fixedInlet and Intialconditions, I have enclosed these files in this comment
[fixedInlet.txt](https://github.com/blueCFD/Core/files/1183680/fixedInlet.txt)
[initialConditions .txt](https://github.com/blueCFD/Core/files/1183679/initialConditions.txt)
P.S how did you come to know it was due to the AMI patch velocity

**Comment by wyldckat** [comment] 2017-07-28 17:04
I'm somewhat familiar with this kind of error message and that `cyclicAMI` is of type coupled. When in doubt, you can check the source code documentation for each boundary type, e.g. for `cyclicAMI`: https://cpp.openfoam.org/v4/classFoam_1_1cyclicAMIFvPatch.html - notice the _Inheritance diagram for cyclicAMIFvPatch_.


As for the error message, this is very strange, because there is no clear reason for this to be happening. Are you able to run the tutorial case `incompressible/pimpleDyMFoam/propeller`?

It is possible that some other field in the 0 folder is the cause of this problem.

**Comment by novicefoamer** [comment] 2017-07-28 17:36
Yes I was able to run the propeller tutorial.

**Comment by wyldckat** [comment] 2017-07-29 14:42
I did get an email with a comment from you that stated:

> Yes I was able to run the propeller tutorial.

But it seems to either have been deleted somehow or Github simply lost track of it.

I tested the tutorial case `incompressible/pimpleDyMFoam/propeller` with a clean installation of blueCFD-Core yesterday and it worked without problems.

Therefore, the only possible points of failure I can think of are:

 1. Some field file inside the folder "0" has a boundary condition assigned to AMI1 and/or AMI2 that is leading to this problem.

 2. The file `$FOAM_ETC/caseDicts/setConstraintTypes` might be corrupted. You can find a clean copy of it here: https://github.com/blueCFD/OpenFOAM-dev/blob/blueCFD-Core-4.x/etc/caseDicts/setConstraintTypes

 3. If it's neither one of these possibilities, it would be useful if you could somehow provide this case so that I could test it, both on Windows and Linux, to try and isolate the reason as to why this is happening.

**Comment by novicefoamer** [comment] 2017-07-29 18:43
Yes i figured cyclicAMI might be the reason for it(thank you for directing me to that issue), when I am running with my innercylinder, for some reason, the AMI patch is not being created, it said an error remove zero sized patch, when I searched online for the issue, it said include keep patches true, tried that, still the patch is not visible, even after snappyHexmesh, 
Can i get your email id , so that I can send the file.

**Comment by wyldckat** [comment] 2017-07-29 20:10
If you haven't already, please use the contact form at our company's (FSD blueCAPE) website: http://joomla.bluecape.com.pt/index.php?option=com_contact&Itemid=3

You can send a link to a Dropbox or some other file sharing service, if you want me to look into this as soon as possible.

**Comment by novicefoamer** [comment] 2017-07-31 14:32
Hi, 
I have sent a request through the company website.

**Comment by wyldckat** [comment] 2017-07-31 19:44
I've received the case and I've done some diagnosis on the reasons why things aren't working.

So the very first error is as you indicated: if the AMI1 and AMI2 patches have 0 faces assigned to them, and if they are listed in the file `constant/polyMesh/boundary`, then the algorithm gets confused and can't figure out what should be done on those two boundaries. That was why the snGrad error message was given.

If we fix the setting `faceType boundary;` that you had mistyped in `snappyHexMeshDict` for the refinement surface that is later converted to AMI, we get the following error message:
```
AMI: Creating addressing and weights between 4396 source faces and 4460 target faces


--> FOAM FATAL ERROR:
Unable to set source and target faces

    From function void Foam::faceAreaWeightAMI<SourcePatch, TargetPatch>::setNextFaces(Foam::label&, Foam::label&, Foam::label&, const boolList&, Foam::labelList&, const Foam::DynamicList<int>&, bool) const [with SourcePatch = Foam::PrimitivePatch<Foam::face, Foam::SubList, const Foam::Field<Foam::Vector<double> >&>; TargetPatch = Foam::PrimitivePatch<Foam::face, Foam::SubList, const Foam::Field<Foam::Vector<double> >&>; Foam::label = int; Foam::boolList = Foam::List<bool>; Foam::labelList = Foam::List<int>]
    in file ./AMIInterpolation/AMIInterpolation/AMIMethod/faceAreaWeightAMI/faceAreaWeightAMI.C at line 287.

FOAM aborting
```

This is because there are faces in the mesh that could not be matched between each side, since they their faces were meshed on top of another surface. This was because the refinement mesh for the cylinder that is meant to be AMI, would lead the mesher to get confused between the blades and the cylinder, resulting in the cylinder surface mesh get tangled up with the surface mesh of the blades inside the cylinder.

Increasing the mesh refinement should solve the problem, although it will require a lot more cells to mesh that region.


I'm planning on closing this issue, since this is mostly a usage issue.
Nonetheless, I'm leaving it open for now to make the following note to report this to the Foundation if confirmed with the more recent versions of OpenFOAM: **This should be better handled by either `createPatch` or at least better reported by the solver, e.g. reporting when there are AMI patches that have no faces assigned to them.**

**Comment by lukasf1989** [comment] 2020-06-22 08:00
I am using OF v1912 today. The same error message is still being used.

My problem was this:

I had reduced my domain size to save computational time. I still had all old patches in the boundary file. Hence, I had cyclicAMI patches named in the boundary and 0/* files which are not in in the mesh anymore.

I had correctly assigned everything but since OF is looking for something that is not there and then the mentioned error occurs. 

For me it was enough to only remove the patches in the boundary file and keep the patches named in the 0/* files to save time.

Thank you Bruno for your hints.

**Comment by wyldckat** [comment] 2024-07-29 17:21
Am closing this issue, because the OpenFOAM Foundation no longer supports AMI.

**Closed by wyldckat** 2024-07-29 17:21 UTC
Labels: test and submit to OpenFOAM Foundation
