### ISSUE TITLE
renumberMesh in parallel do not consider the change in barycentric coordinates of particles

### ISSUE THREAD

**Issue by AlexLadino** [blueCFD/Core#137] opened 2019-12-02 16:41 UTC
1. I have a time ./0/lagrangian/kinematicCloud (with velocities and positions in the whole domain) in ./case
2. decomposePar -> decompose the case in processor* including the kinematicCloud
3. runParallel renumberMesh -overwrite -> renumber the cells for low reduce matrix bandwith
If you plot the particle positions does not coincide with the original from ./0/lagrangian/...
That is because particle positions in new releases are in barycentric coordinates which depends of the cell numbering that were modified in renumberMesh by it do not reorganize the positions file of the particle cloud.
That can be fixed?

**Comment by wyldckat** [comment] 2019-12-03 11:06
This might already be fixed in the latest OpenFOAM 5.x development repository, but I haven't confirmed this yet.

Could you provide a simple test case with which I can reproduce the issue? This is so that I can test more quickly on Linux with the latest OpenFOAM 5.x, to check if this was already fixed upstream. Because if it has already been fixed upstream, I can more easily provide an update.

**Comment by wyldckat** [comment] 2024-08-13 17:33
Am unable to reproduce and I'm guessing that this is fixed by now.

**Closed by wyldckat** 2024-08-13 17:33 UTC
Labels: bug, test and submit to OpenFOAM Foundation
