### ISSUE TITLE
simpleFoam crashes after a certain number of iterations

### ISSUE THREAD

**Issue by novicefoamer** [blueCFD/Core#44] opened 2017-07-19 14:25 UTC
I have successfully ran a solve in Of2.3x , when I have made the change to OF 4.x the solver runs for a couple of iterations, and it crashes. I have placed the log files in this issue
[log - Copy.txt](https://github.com/blueCFD/Core/files/1159405/log.-.Copy.txt)
Time = 982

smoothSolver:  Solving for Ux, Initial residual = 0.000416201, Final residual = 3.57773e-005, No Iterations 9
smoothSolver:  Solving for Uy, Initial residual = 0.00438673, Final residual = 0.000369901, No Iterations 9
smoothSolver:  Solving for Uz, Initial residual = 0.000850212, Final residual = 7.4449e-005, No Iterations 9
GAMG:  Solving for p, Initial residual = 0.00376223, Final residual = 2.25188e-005, No Iterations 5
time step continuity errors : sum local = 4.39408e-005, global = -2.22125e-007, cumulative = -2.89355e-006
smoothSolver:  Solving for omega, Initial residual = 1.20495e-005, Final residual = 1.15147e-006, No Iterations 3
smoothSolver:  Solving for k, Initial residual = 0.000213519, Final residual = 1.77856e-005, No Iterations 3
ExecutionTime = 32504 s  ClockTime = 32504 s

Time = 983

smoothSolver:  Solving for Ux, Initial residual = 0.000416041, Final residual = 3.59587e-005, No Iterations 9
smoothSolver:  Solving for Uy, Initial residual = 0.00438166, Final residual = 0.00036403, No Iterations 9
smoothSolver:  Solving for Uz, Initial residual = 0.000851117, Final residual = 7.41906e-005, No Iterations 9
GAMG:  Solving for p, Initial residual = 0.00374339, Final residual = 2.40375e-005, No Iterations 5
time step continuity errors : sum local = 4.68002e-005, global = -4.28986e-007, cumulative = -3.32254e-006
smoothSolver:  Solving for omega, Initial residual = 1.20819e-005, Final residual = 1.15997e-006, No Iterations 3
smoothSolver:  Solving for k, Initial residual = 0.000212759, Final residual = 1.78204e-005, No Iterations 3
ExecutionTime = 32537.8 s  ClockTime = 32538 s

Time = 984

smoothSolver:  Solving for Ux, Initial residual = 0.000419994, Final residual = 3.65096e-005, No Iterations 9
smoothSolver:  Solving for Uy, Initial residual = 0.00440355, Final residual = 0.000364008, No Iterations 9
smoothSolver:  Solving for Uz, Initial residual = 0.000854045, Final residual = 7.4039e-005, No Iterations 9
GAMG:  Solving for p, Initial residual = 0.00377404, Final residual = 2.4576e-005, No Iterations 5
time step continuity errors : sum local = 4.77375e-005, global = -6.49328e-007, cumulative = -3.97186e-006
[5] We're sorry, but the application crashed and safe stack tracing isn't available in this current implementation of blueCFD-Core patches for OpenFOAM.

job aborted:
[ranks] message

[0-4] terminated

[5] process exited without calling finalize

---- error analysis -----

[5] on NT66
simpleFoam ended prematurely and may have crashed. exit code 3

---- error analysis -----

**Comment by wyldckat** [comment] 2017-07-19 17:00
984 iterations is a very large couple ;)

This crash is rather unfortunate, namely that we don't have stack trace implemented yet to help figure this out :(

The first detail I want to point out is that you should look at the first 160 lines on the log file, because the warnings given there could potentially influence what's happened here, although I'm hoping this wasn't the situation here.

The second detail is that the case was simulated in parallel... this could have lead to some numerical instability that could otherwise not occur on Linux or vice versa... in other words, something that depends on the platform where it's running.

In particular, since you're using k-omega SST and the crash occurred when it was trying to solve the omega equation, it might have crashed due to an issue I've had in the past when running with this turbulence model in parallel: the omega equation is very sensitive to numerical noise and any _flaw_ that might occur in the syncing between the parallel processes, can lead to the omega values becoming rather _strange_ and _seeing_ non-existing vortices on the "processor.*" patches. If this is the case, one solution is to reduce the relaxation factors for the `omega` and `k` entries down to 0.5 or 0.3.

The other detail that comes up to mind is the fact that it really depends on the version of OpenFOAM 2.3.x that you were using before (was it the one from blueCFD-Core 2.3-1?), because it likely has a bug that was fixed in OpenFOAM 2.4.x: https://bugs.openfoam.org/view.php?id=1724 - this could potentially had some effect on the results and lead to this crash.


Therefore, in review, what I ask you to check is if reducing the relaxation factors for `omega` and `k` entries down to 0.5 or 0.3, helps solve this issue or not.
If it doesn't solve this issue and if possible, could you share a test case with which this issue is reproducible? At the very least I could try running it on Linux and see if it also crashes there or not. If the case cannot be shared in public, please use the following contact form to get the information to me at FSD blueCAPE: http://joomla.bluecape.com.pt/index.php?option=com_contact&Itemid=3

**Comment by novicefoamer** [comment] 2017-07-26 02:18
Thank you Bruno, relaxing the factors worked

**Comment by wyldckat** [comment] 2017-07-26 08:37
Excellent, many thanks for the feedback! I'm closing this issue.

**Closed by wyldckat** 2017-07-26 08:37 UTC
